./query_movie_title.sh --starts 'life of pi'
./query_movie_title.sh 'Life of Pi (2012)'
./query_movie_title.sh 'life of pi (2012)'
./query_movie_title.sh 'Life of Pi'
./query_movie_title.sh 'life of pi'
./query_movie_title.sh 'the devil'
./query_movie_title.sh 'The Devil, Probably'
./query_movie_title.sh 'the devil, probably'
./query_movie_title.sh 'the devil,'
./query_movie_title.sh 'The Life of Oharu (1952)'
./query_movie_title.sh 'The Life of Oharu'
./query_movie_title.sh 'The Life of Oharu'
./query_movie_title.sh 'the Life of Oharu'
./query_movie_title.sh 'the life of oharu'
./query_movie_title.sh 'The Life of Oharu*'
./query_movie_title.sh -x 'The Life of Oharu (1952)'
./query_movie_title.sh -x 'The Life of Oharu'
./query_movie_title.sh -x 'The Life of Oharu*'
./query_movie_title.sh 'The Only Son'
./query_movie_title.sh --aka 'Heart of Glass'
./query_movie_title.sh --aka 'The Devil, Probably'
./query_movie_title.sh --aka 'The Devil,'
./query_movie_title.sh --aka 'The Only Son '
./query_movie_title.sh --aka 'The Only Son'
./query_movie_title.sh --aka 'The Only Son*'
./query_movie_title.sh --aka 'The Only Son,'
./query_movie_title.sh --aka 'Tokyo monogatari'
./query_movie_title.sh --aka 'Tokyo Story'
./query_movie_title.sh --aka 'Tokyo monogatari (1953)'
./query_movie_title.sh --contains 'monogatari'
./query_movie_title.sh --contains 'Prejudice'
./query_movie_title.sh --starts 'Forrest'
./query_movie_title.sh --reverse-aka 'Bande à part'
./query_movie_title.sh --reverse-aka 'Todake no kyodai (1941)'
./query_movie_title.sh 'Le diable probablement (1977)'
./query_movie_title.sh 'Le diable probablement'
./query_movie_title.sh --exact 'Higanbana'
./query_movie_title.sh --ignore-case 'higanbana (1958)'
./query_movie_title.sh --ascii --contains 'bushiko'
./query_movie_title.sh  --contains 'bushiko (1958)'
./query_movie_title.sh  --contains 'bushik_ (1958)'
