./check_director_name.sh "Francois Truffaut"
./check_director_name.sh "Hitchcock, A*"
./check_director_name.sh "Hitchcock, Al*"
./check_director_name.sh "Hitchcock, Alfred"
./check_director_name.sh "Truffaut"
./check_director_name.sh "Truffaut, F*"
./check_director_name.sh "Truffaut, Francois"
./check_director_name.sh "alfred hitchcock"
./check_director_name.sh "hitchcock, alfred"
./check_director_name.sh "Alejandro Gonzalez Inarritu"
./check_director_name.sh "Gonzalez Inarritu, Alejandro"
./check_director_name.sh --exact "Griffith, D.W. (I)"
./check_director_name.sh "Griffith, D.W."
./check_director_name.sh "Francis Ford"
./check_director_name.sh "Ozu, Yasuji*"
./check_director_name.sh "Kurosawa"
./check_director_name.sh "Alejandro González Iñárritu"
./check_director_name.sh --exact "González Iñárritu, Alejandro"
./check_director_name.sh "González Iñárritu, Alejandro"
