./check_movie_title.sh 'life of pi %'
./check_movie_title.sh 'Life of Pi (2012)'
./check_movie_title.sh 'life of pi (2012)'
./check_movie_title.sh 'Life of Pi'
./check_movie_title.sh 'life of pi'
./check_movie_title.sh 'the devil'
./check_movie_title.sh 'The Devil, Probably'
./check_movie_title.sh 'the devil, probably'
./check_movie_title.sh 'the devil,'
./check_movie_title.sh 'The Life of Oharu (1952)'
./check_movie_title.sh 'The Life of Oharu'
./check_movie_title.sh 'The Life of Oharu'
./check_movie_title.sh 'the Life of Oharu'
./check_movie_title.sh 'the life of oharu'
./check_movie_title.sh 'The Life of Oharu*'
./check_movie_title.sh -x 'The Life of Oharu (1952)'
./check_movie_title.sh -x 'The Life of Oharu'
./check_movie_title.sh -x 'The Life of Oharu*'
./check_movie_title.sh 'The Only Son'
./check_movie_title.sh --aka 'Heart of Glass'
./check_movie_title.sh --aka 'The Devil, Probably'
./check_movie_title.sh --aka 'The Devil,'
./check_movie_title.sh --aka 'The Only Son '
./check_movie_title.sh --aka 'The Only Son'
./check_movie_title.sh --aka 'The Only Son*'
./check_movie_title.sh --aka 'The Only Son,'
./check_movie_title.sh --aka 'Tokyo monogatari'
./check_movie_title.sh --aka 'Tokyo Story'
./check_movie_title.sh --aka 'Tokyo monogatari (1953)'
